version = 1
SPDX-PackageName = "metal-credential-sync"
SPDX-PackageSupplier = "CobaltCore authors <ospo@sap.com>"
SPDX-PackageDownloadLocation = "https://github.com/cobaltcore-dev/metal-credential-sync"

[[annotations]]
path = [
    ".devcontainer/**",
    ".github/**",
    ".gitignore",
    ".dockerignore",
    ".golangci.yml",
    ".custom-gcl.yml",
    "CODEOWNERS",
    "Dockerfile",
    "Makefile",
    "PROJECT",
    "config/**",
    "dist/**",
    "go.mod",
    "go.sum",
    "mkdocs.yml",
    "REUSE.toml",
    "hack/**",
    "package.json",
    "package-lock.json",
    "internal/cmd/visualizer/index.html",
    "test/data/*.json",
    "test/data/*.yaml",
    "api/v1alpha1/zz_generated.deepcopy.go"
]
precedence = "aggregate"
SPDX-FileCopyrightText = "2026 SAP SE or an SAP affiliate company and CobaltCore contributors"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [
    "docs/**",
    "README.md",
    "AGENTS.md",
    "CLAUDE.md",
    "IMPLEMENTATION.md"
]
precedence = "aggregate"
SPDX-FileCopyrightText = "2026 SAP SE or an SAP affiliate company and CobaltCore contributors"
SPDX-License-Identifier = "Apache-2.0"
