# SPDX-FileCopyrightText: 2024 SAP SE or an SAP affiliate company and IronCore contributors
# SPDX-License-Identifier: Apache-2.0

name: Tests

on:
  pull_request:
    types: [assigned, opened, synchronize, reopened]
    paths-ignore:
      - 'docs/**'
      - '**/*.md'

jobs:
  test:
    name: Run unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Clone the code
        uses: actions/checkout@v6

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
          cache: true

      - name: Download dependencies
        run: go mod download

      - name: Run tests
        run: make test

      - name: Upload coverage report
        uses: codecov/codecov-action@v4
        if: always()
        with:
          file: ./cover.out
          flags: unittests
          fail_ci_if_error: false
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
